### ISSUE TITLE
Distribute k8 nodes across Hetzner data centers

### ISSUE THREAD

**Issue by ranguard** [metacpan/metacpan-k8s#58]
Currently everything in Frankfurt - but they have Neurenburg DC as well, so might be good to put one of the nodes there for resilience.

**Comment by ssoriche** [comment]
Spreading nodes outside of data centres isn't typically done due to latency and split brain syndrome. If we need that kind of redundancy we create multiple clusters. Typically this is not worth the cost. When we move off the other data centres we can rebuild them to be separate clusters for redundancy.

**Comment by ranguard** [comment]
> Spreading nodes outside of data centres isn't typically done due to latency and split brain syndrome. If we need that kind of redundancy we create multiple clusters. Typically this is not worth the cost. When we move off the other data centres we can rebuild them to be separate clusters for redundancy.

Sounds good - closing
